In [2]:
import pandas as pd

data = {
    'Product': ['Pen', 'Pencil', 'Notebook', 'Eraser', 'Marker', 'Scale', 'Bag', 'Bottle'],
    'Category': ['Stationery', 'Stationery', 'Stationery', 'Stationery', 'Stationery', 'Stationery', 'Accessories', 'Accessories'],
    'Sales': [200, 100, 600, 50, 300, 150, 1200, 800],
    'Profit': [50, 20, 150, 10, 80, 30, 300, 200],
    'Region': ['South', 'North', 'South', 'East', 'West', 'North', 'South', 'East']
}

df = pd.DataFrame(data)
df

    Product     Category  Sales  Profit Region
0       Pen   Stationery    200      50  South
1    Pencil   Stationery    100      20  North
2  Notebook   Stationery    600     150  South
3    Eraser   Stationery     50      10   East
4    Marker   Stationery    300      80   West
5     Scale   Stationery    150      30  North
6       Bag  Accessories   1200     300  South
7    Bottle  Accessories    800     200   East

In [7]:
df[['Product','Sales']]
#This shows only product names and their sales values

    Product  Sales
0       Pen    200
1    Pencil    100
2  Notebook    600
3    Eraser     50
4    Marker    300
5     Scale    150
6       Bag   1200
7    Bottle    800

In [8]:
df[df['Sales']>df['Sales'].mean()]
#This shows products with sales higher than the average sales value.

    Product     Category  Sales  Profit Region
2  Notebook   Stationery    600     150  South
6       Bag  Accessories   1200     300  South
7    Bottle  Accessories    800     200   East

In [9]:
df.sort_values(by='Sales',ascending=False)
#This sorts the dataset from highest to lowest sales.

    Product     Category  Sales  Profit Region
6       Bag  Accessories   1200     300  South
7    Bottle  Accessories    800     200   East
2  Notebook   Stationery    600     150  South
4    Marker   Stationery    300      80   West
0       Pen   Stationery    200      50  South
5     Scale   Stationery    150      30  North
1    Pencil   Stationery    100      20  North
3    Eraser   Stationery     50      10   East

In [10]:
df[(df['Sales']>200) & (df['Profit']>50)]
#This shows products that have both high sales and high profit.

    Product     Category  Sales  Profit Region
2  Notebook   Stationery    600     150  South
4    Marker   Stationery    300      80   West
6       Bag  Accessories   1200     300  South
7    Bottle  Accessories    800     200   East