In [40]:
import pandas as pd

In [41]:
df=pd.read_csv(r"C:\Users\acer\OneDrive\Desktop\day03 messy dataset.csv")

In [42]:
print(df)

    Order_ID Customer_Name        City     Product     Category  Order_Date  \
0       1001         Arjun       Kochi      Laptop  Electronics  05-01-2024
1       1002         Meera  Trivandrum       Phone  Electronics  06-01-2024
2       1003         Rahul       Kochi  Headphones  Electronics  05-01-2024
3       1004           Anu   Kozhikode      Laptop  Electronics  07-01-2024
4       1005         Arjun       Kochi      Laptop  Electronics  05-01-2024
5       1006           NaN       Kochi      Tablet  Electronics  08-01-2024
6       1007         David       Kochi         NaN  Electronics  09-01-2024
7       1008          Neha       Kochi       Phone  Electronics  10-01-2024
8       1009          Asha  Trivandrum       Chair    Furniture  11-01-2024
9       1010          Ravi       Kochi       Table    Furniture  12-01-2024
10      1011         Meera  Trivandrum       Phone  Electronics  06-01-2024
11      1012          John       Kochi      Laptop  Electronics  13-01-2024
12      1013           Anu   Kozhikode       Chair    Furniture  14-01-2024
13      1014         Rahul       Kochi  Headphones  Electronics  15-01-2024
14      1015          Asha  Trivandrum         NaN    Furniture  16-01-2024
15      1016          Ravi       Kochi       Table    Furniture  17-01-2024
16      1017          Neha       Kochi       Phone  Electronics  18-01-2024
17      1018         David       Kochi      Tablet  Electronics  19-01-2024
18      1019           NaN       Kochi      Laptop  Electronics  20-01-2024
19      1020         Arjun       Kochi      Laptop  Electronics  05-01-2024
20      1021         Meera  Trivandrum       Phone  Electronics  21-01-2024
21      1022         Rahul       Kochi  Headphones  Electronics  22-01-2024
22      1023           Anu   Kozhikode      Laptop  Electronics  23-01-2024
23      1024          Asha  Trivandrum       Chair    Furniture  24-01-2024
24      1025          Ravi       Kochi       Table    Furniture  25-01-2024
25      1026          Neha       Kochi       Phone  Electronics  26-01-2024
26      1027         David       Kochi      Tablet  Electronics  27-01-2024
27      1028          John       Kochi      Laptop  Electronics  28-01-2024
28      1029           Anu   Kozhikode       Chair    Furniture  29-01-2024
29      1030         Rahul       Kochi  Headphones  Electronics  30-01-2024
30      1031          Asha  Trivandrum       Chair    Furniture  31-01-2024
31      1032          Ravi       Kochi       Table    Furniture  01-02-2024
32      1033          Neha       Kochi       Phone  Electronics  02-02-2024
33      1034         David       Kochi      Tablet  Electronics  03-02-2024
34      1035          John       Kochi      Laptop  Electronics  04-02-2024
35      1036           Anu   Kozhikode       Chair    Furniture  05-02-2024
36      1037         Rahul       Kochi  Headphones  Electronics  06-02-2024
37      1038          Asha  Trivandrum       Chair    Furniture  07-02-2024
38      1039          Ravi       Kochi       Table    Furniture  08-02-2024
39      1040          Neha       Kochi       Phone  Electronics  09-02-2024
40      1041         David       Kochi      Tablet  Electronics  10-02-2024
41      1042          John       Kochi      Laptop  Electronics  11-02-2024
42      1043           Anu   Kozhikode       Chair    Furniture  12-02-2024
43      1044         Rahul       Kochi  Headphones  Electronics  13-02-2024
44      1045          Asha  Trivandrum       Chair    Furniture  14-02-2024
45      1046          Ravi       Kochi       Table    Furniture  15-02-2024
46      1047          Neha       Kochi       Phone  Electronics  16-02-2024
47      1048         David       Kochi      Tablet  Electronics  17-02-2024
48      1049          John       Kochi      Laptop  Electronics  18-02-2024
49      1050           Anu   Kozhikode       Chair    Furniture  19-02-2024

    Quantity  Price Payment_Method  Rating
0          1  55000    Credit Card       5
1          2  30000     Debit Card       4
2          1   2000           Cash       4
3          1  55000    Credit Card       5
4          1  55000    Credit Card       5
5          1  15000            UPI       3
6          1  12000            UPI       4
7          2  30000     Debit Card       5
8          1   2500           Cash       3
9          1   7000    Credit Card       4
10         2  30000     Debit Card       4
11         1  55000    Credit Card       5
12         1   2500           Cash       3
13         1   2000           Cash       4
14         1   2500           Cash       3
15         1   7000    Credit Card       4
16         2  30000     Debit Card       5
17         1  15000            UPI       3
18         1  55000    Credit Card       5
19         1  55000    Credit Card       5
20         2  30000     Debit Card       4
21         1   2000           Cash       4
22         1  55000    Credit Card       5
23         1   2500           Cash       3
24         1   7000    Credit Card       4
25         2  30000     Debit Card       5
26         1  15000            UPI       3
27         1  55000    Credit Card       5
28         1   2500           Cash       3
29         1   2000           Cash       4
30         1   2500           Cash       3
31         1   7000    Credit Card       4
32         2  30000     Debit Card       5
33         1  15000            UPI       3
34         1  55000    Credit Card       5
35         1   2500           Cash       3
36         1   2000           Cash       4
37         1   2500           Cash       3
38         1   7000    Credit Card       4
39         2  30000     Debit Card       5
40         1  15000            UPI       3
41         1  55000    Credit Card       5
42         1   2500           Cash       3
43         1   2000           Cash       4
44         1   2500           Cash       3
45         1   7000    Credit Card       4
46         2  30000     Debit Card       5
47         1  15000            UPI       3
48         1  55000    Credit Card       5
49         1   2500           Cash       3

In [43]:
## Checking missing values to understand which columns need cleaning
df.isnull().sum()

Order_ID          0
Customer_Name     2
City              0
Product           2
Category          0
Order_Date        0
Quantity          0
Price             0
Payment_Method    0
Rating            0
dtype: int64

In [44]:
## Dropping rows where 'product' is missing because it is a key identifier
df=df.dropna(subset=["Product"])
print(df)

    Order_ID Customer_Name        City     Product     Category  Order_Date  \
0       1001         Arjun       Kochi      Laptop  Electronics  05-01-2024
1       1002         Meera  Trivandrum       Phone  Electronics  06-01-2024
2       1003         Rahul       Kochi  Headphones  Electronics  05-01-2024
3       1004           Anu   Kozhikode      Laptop  Electronics  07-01-2024
4       1005         Arjun       Kochi      Laptop  Electronics  05-01-2024
5       1006           NaN       Kochi      Tablet  Electronics  08-01-2024
7       1008          Neha       Kochi       Phone  Electronics  10-01-2024
8       1009          Asha  Trivandrum       Chair    Furniture  11-01-2024
9       1010          Ravi       Kochi       Table    Furniture  12-01-2024
10      1011         Meera  Trivandrum       Phone  Electronics  06-01-2024
11      1012          John       Kochi      Laptop  Electronics  13-01-2024
12      1013           Anu   Kozhikode       Chair    Furniture  14-01-2024
13      1014         Rahul       Kochi  Headphones  Electronics  15-01-2024
15      1016          Ravi       Kochi       Table    Furniture  17-01-2024
16      1017          Neha       Kochi       Phone  Electronics  18-01-2024
17      1018         David       Kochi      Tablet  Electronics  19-01-2024
18      1019           NaN       Kochi      Laptop  Electronics  20-01-2024
19      1020         Arjun       Kochi      Laptop  Electronics  05-01-2024
20      1021         Meera  Trivandrum       Phone  Electronics  21-01-2024
21      1022         Rahul       Kochi  Headphones  Electronics  22-01-2024
22      1023           Anu   Kozhikode      Laptop  Electronics  23-01-2024
23      1024          Asha  Trivandrum       Chair    Furniture  24-01-2024
24      1025          Ravi       Kochi       Table    Furniture  25-01-2024
25      1026          Neha       Kochi       Phone  Electronics  26-01-2024
26      1027         David       Kochi      Tablet  Electronics  27-01-2024
27      1028          John       Kochi      Laptop  Electronics  28-01-2024
28      1029           Anu   Kozhikode       Chair    Furniture  29-01-2024
29      1030         Rahul       Kochi  Headphones  Electronics  30-01-2024
30      1031          Asha  Trivandrum       Chair    Furniture  31-01-2024
31      1032          Ravi       Kochi       Table    Furniture  01-02-2024
32      1033          Neha       Kochi       Phone  Electronics  02-02-2024
33      1034         David       Kochi      Tablet  Electronics  03-02-2024
34      1035          John       Kochi      Laptop  Electronics  04-02-2024
35      1036           Anu   Kozhikode       Chair    Furniture  05-02-2024
36      1037         Rahul       Kochi  Headphones  Electronics  06-02-2024
37      1038          Asha  Trivandrum       Chair    Furniture  07-02-2024
38      1039          Ravi       Kochi       Table    Furniture  08-02-2024
39      1040          Neha       Kochi       Phone  Electronics  09-02-2024
40      1041         David       Kochi      Tablet  Electronics  10-02-2024
41      1042          John       Kochi      Laptop  Electronics  11-02-2024
42      1043           Anu   Kozhikode       Chair    Furniture  12-02-2024
43      1044         Rahul       Kochi  Headphones  Electronics  13-02-2024
44      1045          Asha  Trivandrum       Chair    Furniture  14-02-2024
45      1046          Ravi       Kochi       Table    Furniture  15-02-2024
46      1047          Neha       Kochi       Phone  Electronics  16-02-2024
47      1048         David       Kochi      Tablet  Electronics  17-02-2024
48      1049          John       Kochi      Laptop  Electronics  18-02-2024
49      1050           Anu   Kozhikode       Chair    Furniture  19-02-2024

    Quantity  Price Payment_Method  Rating
0          1  55000    Credit Card       5
1          2  30000     Debit Card       4
2          1   2000           Cash       4
3          1  55000    Credit Card       5
4          1  55000    Credit Card       5
5          1  15000            UPI       3
7          2  30000     Debit Card       5
8          1   2500           Cash       3
9          1   7000    Credit Card       4
10         2  30000     Debit Card       4
11         1  55000    Credit Card       5
12         1   2500           Cash       3
13         1   2000           Cash       4
15         1   7000    Credit Card       4
16         2  30000     Debit Card       5
17         1  15000            UPI       3
18         1  55000    Credit Card       5
19         1  55000    Credit Card       5
20         2  30000     Debit Card       4
21         1   2000           Cash       4
22         1  55000    Credit Card       5
23         1   2500           Cash       3
24         1   7000    Credit Card       4
25         2  30000     Debit Card       5
26         1  15000            UPI       3
27         1  55000    Credit Card       5
28         1   2500           Cash       3
29         1   2000           Cash       4
30         1   2500           Cash       3
31         1   7000    Credit Card       4
32         2  30000     Debit Card       5
33         1  15000            UPI       3
34         1  55000    Credit Card       5
35         1   2500           Cash       3
36         1   2000           Cash       4
37         1   2500           Cash       3
38         1   7000    Credit Card       4
39         2  30000     Debit Card       5
40         1  15000            UPI       3
41         1  55000    Credit Card       5
42         1   2500           Cash       3
43         1   2000           Cash       4
44         1   2500           Cash       3
45         1   7000    Credit Card       4
46         2  30000     Debit Card       5
47         1  15000            UPI       3
48         1  55000    Credit Card       5
49         1   2500           Cash       3

In [45]:
# Filling missing 'Customer_Name' with 'Unknown' as a default category
df["Customer_Name"]=df["Customer_Name"].fillna("Unknown")
df

,Order_ID,Customer_Name,City,Product,Category,Order_Date,Quantity,Price,Payment_Method,Rating
0,1001,Arjun,Kochi,Laptop,Electronics,05-01-2024,1,55000,Credit Card,5
1,1002,Meera,Trivandrum,Phone,Electronics,06-01-2024,2,30000,Debit Card,4
2,1003,Rahul,Kochi,Headphones,Electronics,05-01-2024,1,2000,Cash,4
3,1004,Anu,Kozhikode,Laptop,Electronics,07-01-2024,1,55000,Credit Card,5
4,1005,Arjun,Kochi,Laptop,Electronics,05-01-2024,1,55000,Credit Card,5
5,1006,Unknown,Kochi,Tablet,Electronics,08-01-2024,1,15000,UPI,3
7,1008,Neha,Kochi,Phone,Electronics,10-01-2024,2,30000,Debit Card,5
8,1009,Asha,Trivandrum,Chair,Furniture,11-01-2024,1,2500,Cash,3
9,1010,Ravi,Kochi,Table,Furniture,12-01-2024,1,7000,Credit Card,4
10,1011,Meera,Trivandrum,Phone,Electronics,06-01-2024,2,30000,Debit Card,4
11,1012,John,Kochi,Laptop,Electronics,13-01-2024,1,55000,Credit Card,5
12,1013,Anu,Kozhikode,Chair,Furniture,14-01-2024,1,2500,Cash,3
13,1014,Rahul,Kochi,Headphones,Electronics,15-01-2024,1,2000,Cash,4
15,1016,Ravi,Kochi,Table,Furniture,17-01-2024,1,7000,Credit Card,4
16,1017,Neha,Kochi,Phone,Electronics,18-01-2024,2,30000,Debit Card,5
17,1018,David,Kochi,Tablet,Electronics,19-01-2024,1,15000,UPI,3
18,1019,Unknown,Kochi,Laptop,Electronics,20-01-2024,1,55000,Credit Card,5
19,1020,Arjun,Kochi,Laptop,Electronics,05-01-2024,1,55000,Credit Card,5
20,1021,Meera,Trivandrum,Phone,Electronics,21-01-2024,2,30000,Debit Card,4
21,1022,Rahul,Kochi,Headphones,Electronics,22-01-2024,1,2000,Cash,4
22,1023,Anu,Kozhikode,Laptop,Electronics,23-01-2024,1,55000,Credit Card,5
23,1024,Asha,Trivandrum,Chair,Furniture,24-01-2024,1,2500,Cash,3
24,1025,Ravi,Kochi,Table,Furniture,25-01-2024,1,7000,Credit Card,4
25,1026,Neha,Kochi,Phone,Electronics,26-01-2024,2,30000,Debit Card,5
26,1027,David,Kochi,Tablet,Electronics,27-01-2024,1,15000,UPI,3
27,1028,John,Kochi,Laptop,Electronics,28-01-2024,1,55000,Credit Card,5
28,1029,Anu,Kozhikode,Chair,Furniture,29-01-2024,1,2500,Cash,3
29,1030,Rahul,Kochi,Headphones,Electronics,30-01-2024,1,2000,Cash,4
30,1031,Asha,Trivandrum,Chair,Furniture,31-01-2024,1,2500,Cash,3
31,1032,Ravi,Kochi,Table,Furniture,01-02-2024,1,7000,Credit Card,4
32,1033,Neha,Kochi,Phone,Electronics,02-02-2024,2,30000,Debit Card,5
33,1034,David,Kochi,Tablet,Electronics,03-02-2024,1,15000,UPI,3
34,1035,John,Kochi,Laptop,Electronics,04-02-2024,1,55000,Credit Card,5
35,1036,Anu,Kozhikode,Chair,Furniture,05-02-2024,1,2500,Cash,3
36,1037,Rahul,Kochi,Headphones,Electronics,06-02-2024,1,2000,Cash,4
37,1038,Asha,Trivandrum,Chair,Furniture,07-02-2024,1,2500,Cash,3
38,1039,Ravi,Kochi,Table,Furniture,08-02-2024,1,7000,Credit Card,4
39,1040,Neha,Kochi,Phone,Electronics,09-02-2024,2,30000,Debit Card,5
40,1041,David,Kochi,Tablet,Electronics,10-02-2024,1,15000,UPI,3
41,1042,John,Kochi,Laptop,Electronics,11-02-2024,1,55000,Credit Card,5
42,1043,Anu,Kozhikode,Chair,Furniture,12-02-2024,1,2500,Cash,3
43,1044,Rahul,Kochi,Headphones,Electronics,13-02-2024,1,2000,Cash,4
44,1045,Asha,Trivandrum,Chair,Furniture,14-02-2024,1,2500,Cash,3
45,1046,Ravi,Kochi,Table,Furniture,15-02-2024,1,7000,Credit Card,4
46,1047,Neha,Kochi,Phone,Electronics,16-02-2024,2,30000,Debit Card,5
47,1048,David,Kochi,Tablet,Electronics,17-02-2024,1,15000,UPI,3
48,1049,John,Kochi,Laptop,Electronics,18-02-2024,1,55000,Credit Card,5
49,1050,Anu,Kozhikode,Chair,Furniture,19-02-2024,1,2500,Cash,3

In [46]:
# Removing duplicate rows to ensure data consistency
df=df.drop_duplicates()
df

,Order_ID,Customer_Name,City,Product,Category,Order_Date,Quantity,Price,Payment_Method,Rating
0,1001,Arjun,Kochi,Laptop,Electronics,05-01-2024,1,55000,Credit Card,5
1,1002,Meera,Trivandrum,Phone,Electronics,06-01-2024,2,30000,Debit Card,4
2,1003,Rahul,Kochi,Headphones,Electronics,05-01-2024,1,2000,Cash,4
3,1004,Anu,Kozhikode,Laptop,Electronics,07-01-2024,1,55000,Credit Card,5
4,1005,Arjun,Kochi,Laptop,Electronics,05-01-2024,1,55000,Credit Card,5
5,1006,Unknown,Kochi,Tablet,Electronics,08-01-2024,1,15000,UPI,3
7,1008,Neha,Kochi,Phone,Electronics,10-01-2024,2,30000,Debit Card,5
8,1009,Asha,Trivandrum,Chair,Furniture,11-01-2024,1,2500,Cash,3
9,1010,Ravi,Kochi,Table,Furniture,12-01-2024,1,7000,Credit Card,4
10,1011,Meera,Trivandrum,Phone,Electronics,06-01-2024,2,30000,Debit Card,4
11,1012,John,Kochi,Laptop,Electronics,13-01-2024,1,55000,Credit Card,5
12,1013,Anu,Kozhikode,Chair,Furniture,14-01-2024,1,2500,Cash,3
13,1014,Rahul,Kochi,Headphones,Electronics,15-01-2024,1,2000,Cash,4
15,1016,Ravi,Kochi,Table,Furniture,17-01-2024,1,7000,Credit Card,4
16,1017,Neha,Kochi,Phone,Electronics,18-01-2024,2,30000,Debit Card,5
17,1018,David,Kochi,Tablet,Electronics,19-01-2024,1,15000,UPI,3
18,1019,Unknown,Kochi,Laptop,Electronics,20-01-2024,1,55000,Credit Card,5
19,1020,Arjun,Kochi,Laptop,Electronics,05-01-2024,1,55000,Credit Card,5
20,1021,Meera,Trivandrum,Phone,Electronics,21-01-2024,2,30000,Debit Card,4
21,1022,Rahul,Kochi,Headphones,Electronics,22-01-2024,1,2000,Cash,4
22,1023,Anu,Kozhikode,Laptop,Electronics,23-01-2024,1,55000,Credit Card,5
23,1024,Asha,Trivandrum,Chair,Furniture,24-01-2024,1,2500,Cash,3
24,1025,Ravi,Kochi,Table,Furniture,25-01-2024,1,7000,Credit Card,4
25,1026,Neha,Kochi,Phone,Electronics,26-01-2024,2,30000,Debit Card,5
26,1027,David,Kochi,Tablet,Electronics,27-01-2024,1,15000,UPI,3
27,1028,John,Kochi,Laptop,Electronics,28-01-2024,1,55000,Credit Card,5
28,1029,Anu,Kozhikode,Chair,Furniture,29-01-2024,1,2500,Cash,3
29,1030,Rahul,Kochi,Headphones,Electronics,30-01-2024,1,2000,Cash,4
30,1031,Asha,Trivandrum,Chair,Furniture,31-01-2024,1,2500,Cash,3
31,1032,Ravi,Kochi,Table,Furniture,01-02-2024,1,7000,Credit Card,4
32,1033,Neha,Kochi,Phone,Electronics,02-02-2024,2,30000,Debit Card,5
33,1034,David,Kochi,Tablet,Electronics,03-02-2024,1,15000,UPI,3
34,1035,John,Kochi,Laptop,Electronics,04-02-2024,1,55000,Credit Card,5
35,1036,Anu,Kozhikode,Chair,Furniture,05-02-2024,1,2500,Cash,3
36,1037,Rahul,Kochi,Headphones,Electronics,06-02-2024,1,2000,Cash,4
37,1038,Asha,Trivandrum,Chair,Furniture,07-02-2024,1,2500,Cash,3
38,1039,Ravi,Kochi,Table,Furniture,08-02-2024,1,7000,Credit Card,4
39,1040,Neha,Kochi,Phone,Electronics,09-02-2024,2,30000,Debit Card,5
40,1041,David,Kochi,Tablet,Electronics,10-02-2024,1,15000,UPI,3
41,1042,John,Kochi,Laptop,Electronics,11-02-2024,1,55000,Credit Card,5
42,1043,Anu,Kozhikode,Chair,Furniture,12-02-2024,1,2500,Cash,3
43,1044,Rahul,Kochi,Headphones,Electronics,13-02-2024,1,2000,Cash,4
44,1045,Asha,Trivandrum,Chair,Furniture,14-02-2024,1,2500,Cash,3
45,1046,Ravi,Kochi,Table,Furniture,15-02-2024,1,7000,Credit Card,4
46,1047,Neha,Kochi,Phone,Electronics,16-02-2024,2,30000,Debit Card,5
47,1048,David,Kochi,Tablet,Electronics,17-02-2024,1,15000,UPI,3
48,1049,John,Kochi,Laptop,Electronics,18-02-2024,1,55000,Credit Card,5
49,1050,Anu,Kozhikode,Chair,Furniture,19-02-2024,1,2500,Cash,3

In [47]:
#to check the data types
df.dtypes

Order_ID           int64
Customer_Name     object
City              object
Product           object
Category          object
Order_Date        object
Quantity           int64
Price              int64
Payment_Method    object
Rating             int64
dtype: object

In [48]:
#To convert data type of 'Order_Date' to datetime for correct analysis
df["Order_Date"] = pd.to_datetime(df["Order_Date"],errors="coerce")
print(df)

    Order_ID Customer_Name        City     Product     Category Order_Date  \
0       1001         Arjun       Kochi      Laptop  Electronics 2024-05-01
1       1002         Meera  Trivandrum       Phone  Electronics 2024-06-01
2       1003         Rahul       Kochi  Headphones  Electronics 2024-05-01
3       1004           Anu   Kozhikode      Laptop  Electronics 2024-07-01
4       1005         Arjun       Kochi      Laptop  Electronics 2024-05-01
5       1006       Unknown       Kochi      Tablet  Electronics 2024-08-01
7       1008          Neha       Kochi       Phone  Electronics 2024-10-01
8       1009          Asha  Trivandrum       Chair    Furniture 2024-11-01
9       1010          Ravi       Kochi       Table    Furniture 2024-12-01
10      1011         Meera  Trivandrum       Phone  Electronics 2024-06-01
11      1012          John       Kochi      Laptop  Electronics        NaT
12      1013           Anu   Kozhikode       Chair    Furniture        NaT
13      1014         Rahul       Kochi  Headphones  Electronics        NaT
15      1016          Ravi       Kochi       Table    Furniture        NaT
16      1017          Neha       Kochi       Phone  Electronics        NaT
17      1018         David       Kochi      Tablet  Electronics        NaT
18      1019       Unknown       Kochi      Laptop  Electronics        NaT
19      1020         Arjun       Kochi      Laptop  Electronics 2024-05-01
20      1021         Meera  Trivandrum       Phone  Electronics        NaT
21      1022         Rahul       Kochi  Headphones  Electronics        NaT
22      1023           Anu   Kozhikode      Laptop  Electronics        NaT
23      1024          Asha  Trivandrum       Chair    Furniture        NaT
24      1025          Ravi       Kochi       Table    Furniture        NaT
25      1026          Neha       Kochi       Phone  Electronics        NaT
26      1027         David       Kochi      Tablet  Electronics        NaT
27      1028          John       Kochi      Laptop  Electronics        NaT
28      1029           Anu   Kozhikode       Chair    Furniture        NaT
29      1030         Rahul       Kochi  Headphones  Electronics        NaT
30      1031          Asha  Trivandrum       Chair    Furniture        NaT
31      1032          Ravi       Kochi       Table    Furniture 2024-01-02
32      1033          Neha       Kochi       Phone  Electronics 2024-02-02
33      1034         David       Kochi      Tablet  Electronics 2024-03-02
34      1035          John       Kochi      Laptop  Electronics 2024-04-02
35      1036           Anu   Kozhikode       Chair    Furniture 2024-05-02
36      1037         Rahul       Kochi  Headphones  Electronics 2024-06-02
37      1038          Asha  Trivandrum       Chair    Furniture 2024-07-02
38      1039          Ravi       Kochi       Table    Furniture 2024-08-02
39      1040          Neha       Kochi       Phone  Electronics 2024-09-02
40      1041         David       Kochi      Tablet  Electronics 2024-10-02
41      1042          John       Kochi      Laptop  Electronics 2024-11-02
42      1043           Anu   Kozhikode       Chair    Furniture 2024-12-02
43      1044         Rahul       Kochi  Headphones  Electronics        NaT
44      1045          Asha  Trivandrum       Chair    Furniture        NaT
45      1046          Ravi       Kochi       Table    Furniture        NaT
46      1047          Neha       Kochi       Phone  Electronics        NaT
47      1048         David       Kochi      Tablet  Electronics        NaT
48      1049          John       Kochi      Laptop  Electronics        NaT
49      1050           Anu   Kozhikode       Chair    Furniture        NaT

    Quantity  Price Payment_Method  Rating
0          1  55000    Credit Card       5
1          2  30000     Debit Card       4
2          1   2000           Cash       4
3          1  55000    Credit Card       5
4          1  55000    Credit Card       5
5          1  15000            UPI       3
7          2  30000     Debit Card       5
8          1   2500           Cash       3
9          1   7000    Credit Card       4
10         2  30000     Debit Card       4
11         1  55000    Credit Card       5
12         1   2500           Cash       3
13         1   2000           Cash       4
15         1   7000    Credit Card       4
16         2  30000     Debit Card       5
17         1  15000            UPI       3
18         1  55000    Credit Card       5
19         1  55000    Credit Card       5
20         2  30000     Debit Card       4
21         1   2000           Cash       4
22         1  55000    Credit Card       5
23         1   2500           Cash       3
24         1   7000    Credit Card       4
25         2  30000     Debit Card       5
26         1  15000            UPI       3
27         1  55000    Credit Card       5
28         1   2500           Cash       3
29         1   2000           Cash       4
30         1   2500           Cash       3
31         1   7000    Credit Card       4
32         2  30000     Debit Card       5
33         1  15000            UPI       3
34         1  55000    Credit Card       5
35         1   2500           Cash       3
36         1   2000           Cash       4
37         1   2500           Cash       3
38         1   7000    Credit Card       4
39         2  30000     Debit Card       5
40         1  15000            UPI       3
41         1  55000    Credit Card       5
42         1   2500           Cash       3
43         1   2000           Cash       4
44         1   2500           Cash       3
45         1   7000    Credit Card       4
46         2  30000     Debit Card       5
47         1  15000            UPI       3
48         1  55000    Credit Card       5
49         1   2500           Cash       3

In [49]:
#To fill the missing values in 'Order_Date'
df["Order_Date"]=df["Order_Date"].fillna(method="ffill")
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 48 entries, 0 to 49
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order_ID        48 non-null     int64
 1   Customer_Name   48 non-null     object
 2   City            48 non-null     object
 3   Product         48 non-null     object
 4   Category        48 non-null     object
 5   Order_Date      48 non-null     datetime64[ns]
 6   Quantity        48 non-null     int64
 7   Price           48 non-null     int64
 8   Payment_Method  48 non-null     object
 9   Rating          48 non-null     int64
dtypes: datetime64[ns](1), int64(4), object(5)
memory usage: 4.1+ KB

C:\Users\acer\AppData\Local\Temp\ipykernel_14052\4123301043.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Order_Date"]=df["Order_Date"].fillna(method="ffill")

In [50]:
print(df)

    Order_ID Customer_Name        City     Product     Category Order_Date  \
0       1001         Arjun       Kochi      Laptop  Electronics 2024-05-01
1       1002         Meera  Trivandrum       Phone  Electronics 2024-06-01
2       1003         Rahul       Kochi  Headphones  Electronics 2024-05-01
3       1004           Anu   Kozhikode      Laptop  Electronics 2024-07-01
4       1005         Arjun       Kochi      Laptop  Electronics 2024-05-01
5       1006       Unknown       Kochi      Tablet  Electronics 2024-08-01
7       1008          Neha       Kochi       Phone  Electronics 2024-10-01
8       1009          Asha  Trivandrum       Chair    Furniture 2024-11-01
9       1010          Ravi       Kochi       Table    Furniture 2024-12-01
10      1011         Meera  Trivandrum       Phone  Electronics 2024-06-01
11      1012          John       Kochi      Laptop  Electronics 2024-06-01
12      1013           Anu   Kozhikode       Chair    Furniture 2024-06-01
13      1014         Rahul       Kochi  Headphones  Electronics 2024-06-01
15      1016          Ravi       Kochi       Table    Furniture 2024-06-01
16      1017          Neha       Kochi       Phone  Electronics 2024-06-01
17      1018         David       Kochi      Tablet  Electronics 2024-06-01
18      1019       Unknown       Kochi      Laptop  Electronics 2024-06-01
19      1020         Arjun       Kochi      Laptop  Electronics 2024-05-01
20      1021         Meera  Trivandrum       Phone  Electronics 2024-05-01
21      1022         Rahul       Kochi  Headphones  Electronics 2024-05-01
22      1023           Anu   Kozhikode      Laptop  Electronics 2024-05-01
23      1024          Asha  Trivandrum       Chair    Furniture 2024-05-01
24      1025          Ravi       Kochi       Table    Furniture 2024-05-01
25      1026          Neha       Kochi       Phone  Electronics 2024-05-01
26      1027         David       Kochi      Tablet  Electronics 2024-05-01
27      1028          John       Kochi      Laptop  Electronics 2024-05-01
28      1029           Anu   Kozhikode       Chair    Furniture 2024-05-01
29      1030         Rahul       Kochi  Headphones  Electronics 2024-05-01
30      1031          Asha  Trivandrum       Chair    Furniture 2024-05-01
31      1032          Ravi       Kochi       Table    Furniture 2024-01-02
32      1033          Neha       Kochi       Phone  Electronics 2024-02-02
33      1034         David       Kochi      Tablet  Electronics 2024-03-02
34      1035          John       Kochi      Laptop  Electronics 2024-04-02
35      1036           Anu   Kozhikode       Chair    Furniture 2024-05-02
36      1037         Rahul       Kochi  Headphones  Electronics 2024-06-02
37      1038          Asha  Trivandrum       Chair    Furniture 2024-07-02
38      1039          Ravi       Kochi       Table    Furniture 2024-08-02
39      1040          Neha       Kochi       Phone  Electronics 2024-09-02
40      1041         David       Kochi      Tablet  Electronics 2024-10-02
41      1042          John       Kochi      Laptop  Electronics 2024-11-02
42      1043           Anu   Kozhikode       Chair    Furniture 2024-12-02
43      1044         Rahul       Kochi  Headphones  Electronics 2024-12-02
44      1045          Asha  Trivandrum       Chair    Furniture 2024-12-02
45      1046          Ravi       Kochi       Table    Furniture 2024-12-02
46      1047          Neha       Kochi       Phone  Electronics 2024-12-02
47      1048         David       Kochi      Tablet  Electronics 2024-12-02
48      1049          John       Kochi      Laptop  Electronics 2024-12-02
49      1050           Anu   Kozhikode       Chair    Furniture 2024-12-02

    Quantity  Price Payment_Method  Rating
0          1  55000    Credit Card       5
1          2  30000     Debit Card       4
2          1   2000           Cash       4
3          1  55000    Credit Card       5
4          1  55000    Credit Card       5
5          1  15000            UPI       3
7          2  30000     Debit Card       5
8          1   2500           Cash       3
9          1   7000    Credit Card       4
10         2  30000     Debit Card       4
11         1  55000    Credit Card       5
12         1   2500           Cash       3
13         1   2000           Cash       4
15         1   7000    Credit Card       4
16         2  30000     Debit Card       5
17         1  15000            UPI       3
18         1  55000    Credit Card       5
19         1  55000    Credit Card       5
20         2  30000     Debit Card       4
21         1   2000           Cash       4
22         1  55000    Credit Card       5
23         1   2500           Cash       3
24         1   7000    Credit Card       4
25         2  30000     Debit Card       5
26         1  15000            UPI       3
27         1  55000    Credit Card       5
28         1   2500           Cash       3
29         1   2000           Cash       4
30         1   2500           Cash       3
31         1   7000    Credit Card       4
32         2  30000     Debit Card       5
33         1  15000            UPI       3
34         1  55000    Credit Card       5
35         1   2500           Cash       3
36         1   2000           Cash       4
37         1   2500           Cash       3
38         1   7000    Credit Card       4
39         2  30000     Debit Card       5
40         1  15000            UPI       3
41         1  55000    Credit Card       5
42         1   2500           Cash       3
43         1   2000           Cash       4
44         1   2500           Cash       3
45         1   7000    Credit Card       4
46         2  30000     Debit Card       5
47         1  15000            UPI       3
48         1  55000    Credit Card       5
49         1   2500           Cash       3